# Generated by Django 3.1.1 on 2020-09-26 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0003_auto_20200920_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 1), (-1, -1)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.link')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 1), (-1, -1)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.comment')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='linkvote',
            constraint=models.UniqueConstraint(fields=('content_object', 'voter'), name='link_voter'),
        ),
        migrations.AddConstraint(
            model_name='commentvote',
            constraint=models.UniqueConstraint(fields=('content_object', 'voter'), name='comment_voter'),
        ),
    ]
